# -*- coding: utf-8 -*-
"""titanic_ds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mr9I3G1I3AmB-FHcOiyIR_YGut4ZV-ns
"""
import joblib


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

df = sns.load_dataset("titanic")

df = df.drop(columns = ['who', 'alive', 'adult_male', 'deck','alone','embark_town' , 'class'])
df['relatives'] = df['sibsp'] + df['parch']
df = df.drop(columns = ['sibsp', 'parch'])
df['age'].fillna(df['age'].median(), inplace=True)
df['embarked'].fillna(df['embarked'].mode()[0], inplace=True)
df['sex'] = df['sex'].map({'male': 0, 'female': 1})
df['embarked'] = df['embarked'].map({'S': 0, 'C': 1, 'Q': 2})

print(df)

X = df.drop("survived", axis=1)
y = df["survived"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.02, random_state= 42)


model = LogisticRegression(max_iter=5000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
predictions = pd.DataFrame(y_pred, columns=["Predicted_Survived"])
results = pd.concat([X_test.reset_index(drop=True), predictions], axis=1)
print(results.head())


plt.show()

test = pd.DataFrame([{'pclass' : 2 , 'sex': 0 , 'age' : 40 , 'fare' : 7.5000 , 'embarked' : 2 , 'relatives' : 5 }])
print(model.predict_proba(test))

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

joblib.dump(model, "titanic_model.pkl")
